version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    restart: always
    environment:
      RAILS_ENV: development
    networks:
      art_serch_network:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      art_serch_network:
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      art_serch_network:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      art_serch_network:

  redis:
    image: redis:6.0.8
    restart: always
    networks:
      art_serch_network:
volumes:
  gem_cache:
  db_data:
  node_modules:

networks:
  art_serch_network:
