version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    ports:
      - "3000:8080"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    restart: always
    environment:
      RAILS_ENV: development
    networks:
      art_serch_network:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      art_serch_network:

  redis:
    image: redis:6.0.8
    restart: always
    networks:
      art_serch_network:
volumes:
  gem_cache:
  db_data:
  node_modules:

networks:
  art_serch_network:
