development:
  adapter: redis
  host:  <%= ENV.fetch("REDIS_HOST", "localhost") %>
  port: <%= ENV.fetch("REDIS_PORT", "6379")  %>
  channel_prefix: art_search_development

test:
  adapter: test

production:
  adapter: redis
  host:  <%= ENV.fetch("REDIS_HOST", "localhost") %>
  port: <%= ENV.fetch("REDIS_PORT", "6379")  %>
  channel_prefix: art_search_production
